"""AWAITING_DM.md — every row currently in "Awaiting DM" status, oldest first.

Every one of these rows is blocked on a HUMAN action, not the pipeline: the
extraction detected a comment-gate ("comment X and I'll DM you...") and the
user has to actually go do that DM, then attach the resulting resource via
/attach. Nothing here will ever be resolved by a script — it's a worklist, not
a backlog. Sorted oldest-first specifically so the ones that have been sitting
longest surface at the top instead of getting buried by newer captures.

Free (zero Gemini calls) — pure Notion property read. Regenerate on demand;
the file itself is gitignored and reflects live Notion state at the moment
it's run, exactly like TAXONOMY_DRIFT.md.

Usage:
    python scripts/awaiting_dm_report.py
    python scripts/awaiting_dm_report.py --out custom_path.md
"""
from __future__ import annotations

import argparse
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("reelbrain.awaiting_dm_report")

AWAITING_DM_STATUS = "⏳ Awaiting DM"
DEFAULT_OUTPUT = "AWAITING_DM.md"


def _posted_or_created(page: dict, props: dict) -> str:
    """'Posted at' when the reel's own post date is known, else the page's
    CAPTURE date (created_time) -- always present, so every row sorts
    meaningfully even for old rows saved before 'Posted at' existed."""
    posted = (props.get("Posted at") or {}).get("date") or {}
    if posted.get("start"):
        return posted["start"]
    return page.get("created_time", "")


def collect_rows(pages: list[dict]) -> list[dict]:
    from app import notion_writer

    rows = []
    for page in pages:
        fields = notion_writer.extract_saves_fields(page)
        if not fields["shortcode"] or fields["status_label"] != AWAITING_DM_STATUS:
            continue
        props = page.get("properties", {})
        rows.append({
            "shortcode": fields["shortcode"],
            "title": fields["title"] or fields["shortcode"],
            "gate_keyword": fields["gate_keyword"] or "",
            "date": _posted_or_created(page, props),
            "permalink": fields["permalink"] or f"https://www.instagram.com/reel/{fields['shortcode']}/",
        })
    # Oldest first; a missing/unparseable date sorts last rather than crashing
    # or silently floating to the top.
    rows.sort(key=lambda r: r["date"] or "9999")
    return rows


def render_markdown(rows: list[dict], generated_at: Optional[datetime] = None) -> str:
    generated_at = generated_at or datetime.now(timezone.utc)
    stamp = generated_at.strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# AWAITING_DM.md — rows waiting on a manual comment + DM",
        "",
        f"Regenerated by `scripts/awaiting_dm_report.py` at {stamp}. "
        f"Sorted oldest first — these are the ones that have waited longest.",
        "",
        f"**{len(rows)} row(s) waiting.**",
        "",
    ]
    if not rows:
        lines.append("Nothing waiting — every gated row has been actioned.")
        return "\n".join(lines) + "\n"

    lines += ["| Date | Title | Comment | Reel |", "|---|---|---|---|"]
    for r in rows:
        date = (r["date"] or "?")[:10]
        title = r["title"].replace("|", "\\|").replace("\n", " ")[:70]
        keyword = r["gate_keyword"].replace("|", "\\|") or "?"
        lines.append(f"| {date} | {title} | `{keyword}` | [{r['shortcode']}]({r['permalink']}) |")
    return "\n".join(lines) + "\n"


def generate(out_path: str = DEFAULT_OUTPUT) -> dict:
    from app import notion_writer

    pages = notion_writer.find_saves_pages_since("1970-01-01T00:00:00")
    rows = collect_rows(pages)
    markdown = render_markdown(rows)
    Path(out_path).write_text(markdown, encoding="utf-8")
    return {"rows": len(rows), "path": out_path}


def main() -> None:
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, OSError):
        pass
    logging.basicConfig(level=logging.WARNING)

    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", default=DEFAULT_OUTPUT, help="output path (default: AWAITING_DM.md)")
    args = parser.parse_args()

    result = generate(args.out)
    print(f"{result['rows']} row(s) awaiting DM -> {result['path']}")


if __name__ == "__main__":
    main()
