"""Implementation Scout — input gatherer + Scout-pick publisher.

LOCAL-ONLY. Two jobs:

1. (default) Gather everything the Scout needs to rank build-worthy automations
   into ONE file, `scout_input.md` in the vault root:
     - every reel note in {vault}/reels/ whose frontmatter says `priority: High`
     - every resource note in {vault}/resources/
     - {vault}/INSTALLED.md (may not exist yet — treated as empty)
   Size-capped at MAX_INPUT_CHARS (~150k): when truncating, High-priority reel
   notes are kept newest-first, then resources newest-first — the oldest
   content is what falls off.

   Then run the Scout itself with:
       claude -p "$(cat SCOUT_PROMPT.md)"
   (from the repo root; SCOUT_PROMPT.md tells the model where scout_input.md
   and the output IMPLEMENTATION_QUEUE.md live).

2. `--push-pick`: read the vault's IMPLEMENTATION_QUEUE.md (the Scout's own
   output) and publish its #1 ranked item to a small persistent Notion page
   ("🔭 Scout Pick") under NOTION_PARENT_PAGE_ID. WHY Notion and not the vault
   file directly: the daily digest runs on Render (GitHub Actions hits the
   deployed /daily-digest endpoint), which has no access to this machine's
   Obsidian vault — Notion is the only store both sides can reach. The digest
   reads that page best-effort for its "Scout pick of the day" line.

Usage:
    python scripts/scout.py                # regenerate scout_input.md
    python scripts/scout.py --push-pick    # publish queue's #1 to Notion
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Optional

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv

load_dotenv()

DEFAULT_VAULT = r"C:\Users\garvb\ReelBrainVault"
MAX_INPUT_CHARS = 150_000
SCOUT_PICK_PAGE_TITLE = "🔭 Scout Pick"
from app.vault_paths import (  # noqa: E402  (after sys.path bootstrap)
    INSTALLED_FILENAME, QUEUE_FILENAME, SCOUT_INPUT_FILENAME,
)

INPUT_FILENAME = SCOUT_INPUT_FILENAME

_PRIORITY_RE = re.compile(r"^priority:\s*High\s*$", re.MULTILINE)


def vault_path() -> Path:
    return Path(os.environ.get("OBSIDIAN_VAULT_PATH", DEFAULT_VAULT))


def _newest_first(paths: list[Path]) -> list[Path]:
    """Reel notes are named YYYY-MM-DD-shortcode.md, so name-descending is
    date-descending; resources fall back to mtime."""
    return sorted(paths, key=lambda p: (p.name, p.stat().st_mtime if p.exists() else 0), reverse=True)


def gather_sections(vault: Path) -> list[tuple[str, str]]:
    """(heading, content) sections in priority order: INSTALLED.md first (it's
    small and the Scout must always see it), then High-priority reels
    newest-first, then resources newest-first."""
    sections: list[tuple[str, str]] = []

    installed = vault / INSTALLED_FILENAME
    installed_text = installed.read_text(encoding="utf-8") if installed.exists() else f"({INSTALLED_FILENAME} does not exist yet — treat as empty)"
    sections.append((INSTALLED_FILENAME, installed_text))

    reels_dir = vault / "reels"
    if reels_dir.exists():
        for path in _newest_first(list(reels_dir.glob("*.md"))):
            text = path.read_text(encoding="utf-8")
            if _PRIORITY_RE.search(text):
                sections.append((f"reels/{path.name}", text))

    resources_dir = vault / "resources"
    if resources_dir.exists():
        for path in _newest_first(list(resources_dir.glob("*.md"))):
            sections.append((f"resources/{path.name}", path.read_text(encoding="utf-8")))

    return sections


def build_input(sections: list[tuple[str, str]], max_chars: int = MAX_INPUT_CHARS) -> str:
    """Concatenate sections under the cap. Sections arrive already priority-
    ordered (see gather_sections), so truncation drops the least important
    tail; a truncated run says so explicitly rather than ending mid-note."""
    parts = ["# Scout input — auto-generated by scripts/scout.py. Do not edit.\n"]
    total = len(parts[0])
    dropped = 0
    for heading, content in sections:
        block = f"\n\n===== {heading} =====\n\n{content.strip()}\n"
        if total + len(block) > max_chars:
            dropped += 1
            continue
        parts.append(block)
        total += len(block)
    if dropped:
        parts.append(f"\n\n===== NOTE =====\n\n({dropped} lower-priority section(s) "
                     f"omitted to stay under the {max_chars}-char cap)\n")
    return "".join(parts)


def first_queue_pick(queue_text: str) -> Optional[str]:
    """The #1 ranked item from IMPLEMENTATION_QUEUE.md: the first '## 1.'-style
    heading (or first '## ' heading after the ranked-list marker), returned as
    its heading line without the hashes."""
    for line in queue_text.splitlines():
        m = re.match(r"^##+\s*(?:1[.):]\s*)(.+)$", line.strip())
        if m:
            return m.group(1).strip()
    # fallback: first level-2 heading that isn't a known non-item section
    for line in queue_text.splitlines():
        m = re.match(r"^##\s+(.+)$", line.strip())
        if m and not m.group(1).lower().startswith(("new since", "already ready", "rules")):
            return m.group(1).strip()
    return None


def push_pick_to_notion(pick: str) -> None:
    from app import notion_writer

    parent = os.environ.get("NOTION_PARENT_PAGE_ID", "").strip()
    if not parent:
        sys.exit("NOTION_PARENT_PAGE_ID not set")
    notion_writer.upsert_named_page(parent, SCOUT_PICK_PAGE_TITLE, [{
        "object": "block", "type": "paragraph",
        "paragraph": {"rich_text": notion_writer._rich_text(pick)},
    }])


def main() -> None:
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, OSError):
        pass

    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--push-pick", action="store_true",
                        help="publish IMPLEMENTATION_QUEUE.md's #1 item to the Notion Scout Pick page")
    args = parser.parse_args()

    vault = vault_path()

    if args.push_pick:
        queue = vault / QUEUE_FILENAME
        if not queue.exists():
            sys.exit(f"{queue} does not exist — run the Scout first (see SCOUT_PROMPT.md)")
        pick = first_queue_pick(queue.read_text(encoding="utf-8"))
        if not pick:
            sys.exit("could not find a #1 ranked item in the queue")
        push_pick_to_notion(pick)
        print(f"published Scout pick to Notion: {pick}")
        return

    sections = gather_sections(vault)
    text = build_input(sections)
    out = vault / INPUT_FILENAME
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out} ({len(text)} chars, {len(sections)} sections gathered)")
    print('next: claude -p "$(cat SCOUT_PROMPT.md)"')


if __name__ == "__main__":
    main()
