"""Monthly vault maintenance — the janitor that keeps the vault honest.

Runs a batch of checks that individually already exist, so nothing here should
surprise the daily pipeline; the point is to run them together on a schedule and
surface anything that needs a human. Ordered so each step sees the previous
step's effects:

  1. Orphan reconnection — reuse vault_orphans.classify(): rebuild stale topic
     indexes, flag reel notes missing tags, flag parentless resources, and
     delete only contentless orphans NOT in an active workflow state (the
     Failed-retry / Awaiting-DM exclusion is enforced inside classify()).
  2. Topic enforcement — enforce_topics for any row that ended up with empty
     Topics (free, zero Gemini). Also upgrades rows stranded on "uncategorized"
     once they have named_entities, same as the daily runner.
  3. Drift detection — flag live tags that look like near-duplicates of a
     canonical tag (drift since Phase 0's merge). Written to TAXONOMY_DRIFT.md.
     REPORT ONLY: never auto-merges — a merge is a priority-sensitive decision
     that goes through the proposal→approve flow, not a monthly script.
  4. Count reconciliation — Notion Saves row count vs vault reel-note count.
  5. Full re-sync.

Safe by default: dry-run unless --apply (matches apply_taxonomy). Monthly, not
nightly — see WORKER_SETUP.md.

Usage:
    python scripts/vault_librarian.py            # dry-run report
    python scripts/vault_librarian.py --apply    # remediate + re-sync
"""
from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path
from typing import Callable

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv

load_dotenv()

from app.taxonomy import find_tag_drift

logger = logging.getLogger("reelbrain.vault_librarian")

DRIFT_REPORT = "TAXONOMY_DRIFT.md"


def write_drift_report(findings: list[dict], path: Path) -> None:
    """Human-review artifact. Empty findings still writes the file (so its
    absence means 'never ran', not 'nothing to report')."""
    lines = ["# TAXONOMY_DRIFT.md — possible near-duplicate tags",
             "",
             "Auto-generated by scripts/vault_librarian.py. **Report only — no "
             "tag was merged.** Each row is a live tag that resembles a canonical "
             "tag; confirm by hand and, if it's a real duplicate, add it to "
             "app/taxonomy.MERGES and re-run apply_taxonomy (which re-checks "
             "priority invariance).",
             ""]
    if not findings:
        lines.append("_No drift detected — every live tag is canonical or clearly distinct._")
    else:
        lines.append("| Live tag | Nearest canonical | Similarity |")
        lines.append("|---|---|---|")
        for f in findings:
            lines.append(f"| `{f['new_tag']}` | `{f['nearest_canonical']}` | {f['score']} |")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def count_reconciliation() -> dict:
    """Notion Saves rows (with a shortcode) vs vault reel notes."""
    from app import notion_writer, obsidian_sync

    pages = notion_writer.find_saves_pages_since("1970-01-01T00:00:00")
    notion_rows = sum(1 for p in pages if notion_writer.extract_digest_fields(p)["shortcode"])
    vault = Path(obsidian_sync.VAULT_PATH)
    vault_notes = len(obsidian_sync.existing_notes_by_shortcode(vault))
    return {"notion_rows": notion_rows, "vault_notes": vault_notes,
            "match": notion_rows == vault_notes, "drift": notion_rows - vault_notes}


def run(dry_run: bool = True, print_fn: Callable[[str], None] = print) -> dict:
    from app import notion_writer, obsidian_sync
    from scripts import enforce_topics, vault_orphans

    vault = Path(obsidian_sync.VAULT_PATH)
    pages = notion_writer.find_saves_pages_since("1970-01-01T00:00:00")

    # 1. Orphans -----------------------------------------------------------------
    report = vault_orphans.classify(vault)
    print_fn(f"Orphans: {len(report['rebuildable_topics'])} topic indexes to rebuild, "
             f"{len(report['reel_needs_tags'])} reels missing tags, "
             f"{len(report['resource_needs_parent'])} parentless resources, "
             f"{len(report['deletable'])} deletable, "
             f"{len(report['retry_protected'])} protected (active workflow).")
    deleted = 0
    if report["deletable"]:
        deleted = vault_orphans.delete_orphans(vault, report["deletable"], dry_run=dry_run, print_fn=print_fn)

    # 2. Topic enforcement (free) ------------------------------------------------
    topicless = enforce_topics.find_topicless_rows(pages, include_upgradable=True)
    print_fn(f"Topic enforcement: {len(topicless)} row(s) need/upgrade topics.")
    enforce_result = enforce_topics.run_enforce(topicless, dry_run=dry_run, print_fn=print_fn) if topicless else {}

    # 3. Drift detection (report only) -------------------------------------------
    live_tags = [t for p in pages for t in notion_writer.extract_digest_fields(p)["topics"]]
    drift = find_tag_drift(live_tags)
    write_drift_report(drift, Path(DRIFT_REPORT))
    print_fn(f"Drift: {len(drift)} possible near-duplicate tag(s) → {DRIFT_REPORT} (report only).")

    # 4. Count reconciliation ----------------------------------------------------
    counts = count_reconciliation()
    verdict = "match" if counts["match"] else f"DRIFT {counts['drift']:+d}"
    print_fn(f"Counts: Notion {counts['notion_rows']} vs vault {counts['vault_notes']} ({verdict}).")

    # 5. Full re-sync ------------------------------------------------------------
    sync_result = {}
    if not dry_run:
        sync_result = obsidian_sync.sync()
        print_fn(f"Re-sync: {sync_result}")

    return {
        "orphans": {k: len(v) if isinstance(v, list) else v for k, v in report.items() if k != "orphans"},
        "orphans_deleted": deleted,
        "topics_enforced": enforce_result,
        "drift_findings": drift,
        "counts": counts,
        "sync": sync_result,
        "dry_run": dry_run,
    }


def main() -> None:
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, OSError):
        pass
    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true",
                        help="remediate + re-sync (default is a dry-run report)")
    args = parser.parse_args()

    result = run(dry_run=not args.apply)
    print("\n" + "=" * 70)
    print(f"vault_librarian {'APPLIED' if args.apply else 'DRY-RUN'}: "
          f"{result['orphans_deleted']} orphans removed, "
          f"{len(result['drift_findings'])} drift finding(s), "
          f"counts {'match' if result['counts']['match'] else 'DRIFT'}.")


if __name__ == "__main__":
    main()
